name: ci

on:
  push:
    paths-ignore:
      - '**/README.md'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Base
        uses: docker/build-push-action@v3
        with:
          context: ./base-notebook
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha,scope=base
          cache-to: type=gha,mode=max,scope=base

      # NOTE: this will use conda package cache from base-notebook b/c same Dockerfile
      - name: Build pangeo-notebook
        uses: docker/build-push-action@v3
        with:
          context: ./pangeo-notebook
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/pangeo-notebook:latest
          cache-from: | 
            type=gha,scope=base
            type=gha,scope=pangeo
          cache-to: type=gha,mode=max,scope=pangeo

      # NOTE: this will use conda package cache from previous steps
      - name: Build pytorch-notebook
        uses: docker/build-push-action@v3
        with:
          context: ./pytorch-notebook
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/pangeo-pytorch:latest
          cache-from: | 
            type=gha,scope=base
            type=gha,scope=pangeo
            type=gha,scope=pytorch
          cache-to: type=gha,mode=max,scope=pytorch
