name: ci

on:
  push:
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      #  with:
      #    buildkitd-flags: --debug

      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build
      #   run: |
      #     buildx build .

      # - name: Bake
      #   uses: docker/bake-action@v2
      #   with:
      #     push: false

      - name: Diagnostics
        run: |
          pwd
          ls
          docker images

      - name: Build Base
        uses: docker/build-push-action@v3
        with:
          context: ./base-notebook
          file: ./Dockerfile
          push: false
          load: true
          tags: pangeo/base:latest
          cache-from: type=gha,scope=base
          cache-to: type=gha,mode=max,scope=base

      # NOTE: this will use conda package cache from base-notebook b/c same Dockerfile
      - name: Build pangeo-notebook
        uses: docker/build-push-action@v3
        with:
          context: ./pangeo-notebook
          file: ./Dockerfile
          push: false
          tags: pangeo/notebook:latest
          cache-from: | 
            type=gha,scope=base
            type=gha,scope=pangeo
          cache-to: type=gha,mode=max,scope=pangeo

      # NOTE: this will use conda package cache from previous steps
      - name: Build pytorch-notebook
        uses: docker/build-push-action@v3
        with:
          context: ./pytorch-notebook
          file: ./Dockerfile
          push: false
          tags: pangeo/pytorch:latest
          cache-from: | 
            type=gha,scope=base
            type=gha,scope=pangeo
            type=gha,scope=pytorch
          cache-to: type=gha,mode=max,scope=pytorch

      - name: List Images
        run: docker images

      - name: List Conda packages
        run: docker run pangeo/base:latest conda list
